name: ReTypeR
options:
  bundleIdPrefix: com.retyper
  deploymentTarget:
    macOS: "15.0"
targets:
  ReTypeR:
    type: application
    platform: macOS
    bundleId: com.retyper.app
    sources:
      - path: Sources
    info:
      path: Info.plist
      properties:
        LSUIElement: true
        CFBundleIconFile: AppIcon.icns
        NSAccessibilityUsageDescription: "ReTypeR нуждается в доступе к функциям Универсального доступа (Accessibility) для чтения выделенного текста и эмуляции нажатий клавиш."
    dependencies:
      - package: KeyboardShortcuts
    settings:
      CODE_SIGN_IDENTITY: "-"
      CODE_SIGN_STYLE: Automatic
      CODE_SIGN_ENTITLEMENTS: ""
      ENABLE_HARDENED_RUNTIME: NO
      MARKETING_VERSION: "1.1.0"
  ReTypeRTests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - path: Tests
    dependencies:
      - target: ReTypeR
    settings:
      GENERATE_INFOPLIST_FILE: YES
packages:
  KeyboardShortcuts:
    url: https://github.com/sindresorhus/KeyboardShortcuts
    from: 2.2.2
